name: Build IP_Finder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential

      - name: Compile main.cpp
        run: g++ -o IP_Finder main.cpp

      - name: Run IP_Finder (optional)
        run: ./IP_Finder
